#!/bin/bash

mysql -h dbhost.cs.man.ac.uk -p 2018_comp10120_y8 << IN

DELETE FROM User;

INSERT INTO User(Username, Name, Email, Password) VALUES 
	("Vlad.Iacob", "Vlad", "email1@email.com", "pass1"),
	("Ben.Rimmer", "Ben","email2@email.com", "pass2"),
	("Juan.Giraldo", "Juan", "email3@email.com", "pass3"),
	("Denislav.Valev", "Denislav", "email4@email.com", "pass4"),
	("Jason.Ozuzu", "Jason", "email5@email.com", "pass5"),
	("Rumaan.Nasir", "Rumaan", "email6@email.com", "pass6"),
	("Michael.Browne", "Michael", "email7@email.com", "pass7");

IN
